# Customer Churn Prediction

## Business Understanding

### Project Overview

Customer churn is one of the most critical challenges faced by subscription-based businesses. Every customer who leaves the company represents not only a loss of current revenue but also the potential loss of future revenue and the investment made to acquire that customer. Since acquiring a new customer is generally more expensive than retaining an existing one, reducing customer churn has become a key business objective for many organizations.

This project aims to develop a machine learning model capable of predicting whether a customer is likely to churn. By identifying high-risk customers in advance, the business can proactively implement retention strategies such as personalized communication, improved customer support, and targeted offers to reduce churn and improve customer loyalty.

Rather than simply building a predictive model, this project focuses on solving a real business problem by combining data analysis, machine learning, and business recommendations.

## Business Problem

Customer churn directly impacts business growth, profitability, and long-term sustainability. A high churn rate reduces recurring revenue, increases customer acquisition costs, and weakens customer lifetime value. If left unmanaged, increasing churn can negatively affect market competitiveness and future business performance.

The business requires an analytical solution that can identify customers who are most likely to leave before they actually churn. Early identification enables different business teams to take proactive actions that improve customer retention and reduce potential revenue loss.

## Business Objectives

The primary objective of this project is to build a machine learning model that accurately predicts customer churn using historical customer information.

Specific objectives include:

* Understand the characteristics of customers who churn.
* Identify the key factors influencing customer churn.
* Build and compare multiple classification models.
* Evaluate model performance using appropriate machine learning metrics.
* Generate actionable business recommendations based on model insights.
* Support data-driven decision making for customer retention strategies.

In [1]:
# ============================================================
# Import Required Libraries
# ============================================================

import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# ============================================================
# Load Dataset
# ============================================================

df = pd.read_csv("../data/WA_Fn-UseC_-Telco-Customer-Churn.csv")

print("Dataset loaded successfully.")

df.head()

Dataset loaded successfully.

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
# ============================================================
# Dataset Information
# ============================================================

print("=" * 60)
print("DATASET SHAPE")
print("=" * 60)

print(df.shape)

print()

print("=" * 60)
print("COLUMN NAMES")
print("=" * 60)

print(df.columns.tolist())

============================================================
DATASET SHAPE
============================================================
(7043, 21)

============================================================
COLUMN NAMES
============================================================
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

In [4]:
# ============================================================
# Dataset Overview
# ============================================================

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [5]:
# ============================================================
# Data Types
# ============================================================

dtype_summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values
})

dtype_summary

              Column Data Type
0         customerID       str
1             gender       str
2      SeniorCitizen     int64
3            Partner       str
4         Dependents       str
5             tenure     int64
6       PhoneService       str
7      MultipleLines       str
8    InternetService       str
9     OnlineSecurity       str
10      OnlineBackup       str
11  DeviceProtection       str
12       TechSupport       str
13       StreamingTV       str
14   StreamingMovies       str
15          Contract       str
16  PaperlessBilling       str
17     PaymentMethod       str
18    MonthlyCharges   float64
19      TotalCharges       str
20             Churn       str

In [6]:
# ============================================================
# Count Data Types
# ============================================================

df.dtypes.value_counts()

str        18
int64       2
float64     1
Name: count, dtype: int64

In [7]:
# ============================================================
# Dataset Shape
# ============================================================

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 7043
Columns : 21

In [8]:
# ============================================================
# First Five Records
# ============================================================

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [9]:
# ============================================================
# Last Five Records
# ============================================================

df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [10]:
# ============================================================
# Random Sample
# ============================================================

df.sample(5, random_state=42)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
185,1024-GUALD,Female,0,Yes,No,1,No,No phone service,DSL,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.8,Yes
2715,0484-JPBRU,Male,0,No,No,41,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45,No
3825,3620-EHIMZ,Female,0,Yes,Yes,52,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.7,No
1807,6910-HADCM,Female,0,No,No,1,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,No,Electronic check,76.35,76.35,Yes
132,8587-XYZSF,Male,0,No,No,67,Yes,No,DSL,No,No,No,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.1,No